### ISSUE TITLE
Docker/Singularity quay.io not found

### ISSUE THREAD

**Issue by mdbarnesUCSD** [cancerit/BRASS#108]
There is an issue with the container being hosted on quay.io. 
When I run:
`singularity pull quay.io/wtsicgp/brass`

I get the following error message:
`FATAL:   While pulling library image: could not get image info: request did not succeed: UNAUTHORIZED: project quay.io not found: project quay.io not found (401 Unauthorized)`

Please let me know if there is an easy way to resolve this, thanks!

**Comment by keiranmraine** [comment]
You must include the version you wish to use as part of the pull. No "latest" images are generated to prevent unintentional upgrades.

**Comment by mdbarnesUCSD** [comment]
I am unfamiliar with Docker/Singularity, but their documentation shows the syntax for pulling a specific release (ie pulling the current release that is v6.3.4):
`singularity pull quay.io/wtsicgp/brass:v6.3.4`
or
`singularity pull quay.io/wtsicgp/brass:6.3.4`

These commands return the same error message as above.

Edit: When using singularity, the following command worked for me:
`singularity pull docker://quay.io/wtsicgp/brass:v6.3.4`

Thanks!
