### ISSUE TITLE
What kind of file does the parameter "-d" require? 

### ISSUE THREAD

**Issue by DingTin** [cancerit/BRASS#116]
Thanks a lot for building up BRASS. But when I tried to use this in docker, as I listed the "-o", "-t" and the '-n" parameters as the examples given in help, the brass.pl requires "-d" and asks it to be "an existing file". Sorry but what kind of file does it requires？
<img width="590" alt="image" src="https://user-images.githubusercontent.com/116635180/232230947-cb0847ad-754b-494f-a50e-e87249274d67.png">

**Comment by quail768** [comment]
Hey @DingTin ,Sorry to bother you. Did you figure it out?
