### ISSUE TITLE
Brass Notation - Understanding Breakpoints

### ISSUE THREAD

**Issue by LB1907** [cancerit/BRASS#120]
Hello,

I have a problem understanding the results. I have already looked in the Wiki under the Bedpe Brass notations, but I didn't understand it.

My problem:

The breakpoints of the lower and higher coordinates are displayed. If I have a translocation and a gene fusion occurs from gene 1 and gene 2, how do I know which side of the chromosome arm is used for the gene fusion from the breakpoints.

Example: Breakpoint 1 in gene 1 is found in intron 1 (1/2) at 15q24.3 and breakpoint 2 in gene 2 is found at 2q11.2 in intron 6 (6/23). Where can I find the information that in chromosome 15 the part of the gene that is on the rest of the long arm (15q24.3-15q26.3) from the breakpoint is fused and in chromosome 2 the part that is attached to the short arm is fused.

I hope that was understandable. I also used the BrassVis program to visualize the data. In a gene fusion where the svclass was specified as "deletion" and where both genes were on the same chromosome and strand, the fusion part of Gen1 was inverted in the image. I would also like to understand why this is the case. For the second question, I have attached a picture to make it easier to understand. 

Thanks in advance!

![BrassVis](https://github.com/cancerit/BRASS/assets/171727118/8e5db4ba-5945-4ea2-a0ac-0a807e62de57)

**Comment by AndyMenzies** [comment]
Hi

I've always thought of the strand info for Brass as a direction of travel. + means moving up the chromosome from low to high coordinate.  -  means moving down the chromosome from high to low coordinate.  Strand 1 gives you the direction you were traveling when you reached the low end of your breakpoint, while Strand 2 gives you the direction you were leaving the high end of the breakpoint.  Therefore a +/+ breakpoint on single chromosome will always be a deletion. 

Brass uses short read sequencing, this limits how far up and down stream we can see to asses the type of SV we've detected.  We won't have a continuous read across a large Structural Variant.  This means that a large cross chromosome insertion will be recorded as 2 cross chromsome break events, each of which will look like a transloaction but we won't be able to tie them together as we can't tell if they are related to eachother.  All we can do is describe the breaks individually. 

I'm not able to answer the question on BrassVis, we didn't develop that tool.

Andy

**Comment by LB1907** [comment]
Thank you for the quick reply. It helped a lot! :)
