### ISSUE TITLE
Option 'normals' has not been defined

### ISSUE THREAD

**Issue by raylim** [cancerit/BRASS#20]
What does this error mean?

```bash
$ brass-group -I extremedepth.bed -F brassRepeats.bed.gz brass/Adcc11T_Adcc11N/tmpBrass/Adcc11T.brm.bam brass/Adcc11T_Adcc11N/tmpBr
ass/Adcc11N.brm.bam | perl-static brassI_pre_filter.pl -i - -t Adcc11T -o brass/Adcc11T_Adcc11N/Adcc11T_vs_Adcc11N.groups
Option 'normals' has not been defined.
```

**Comment by keiranmraine** [comment]
Apologies for the delay.  An element of the `brass.pl` command line args is incorrectly marked as optional:

        -filter    -f   bgzip tabix-ed normal panel groups file

I've added a page to the wiki to help with the creation of this file.

Regards,
Keiran
