### ISSUE TITLE
pstreams/pstream.h: No such file or directory

### ISSUE THREAD

**Issue by komalsrathi** [cancerit/BRASS#25]
I don't have root access and I am using the build from here `https://github.com/cancerit/BRASS/archive/v4.0.5.tar.gz`. 
I cloned pstreams using `git clone git://git.code.sf.net/p/pstreams/code pstreams` in /path/to/BRASS-4.0.5/  because setup.log says it is searching for `pstreams/pstream.h`. But it is still unable to find the pstream.h file.

```
make: Entering directory `/ifs/work/leukgen/opt/BRASS-4.0.5/c++'
g++ -Wall -Wextra -g -I../cansam -O2   -c -o augment-bam.o augment-bam.cpp
augment-bam.cpp:44:30: error: pstreams/pstream.h: No such file or directory
augment-bam.cpp: In function ‘int main(int, char**)’:
augment-bam.cpp:197: error: ‘redi’ has not been declared
augment-bam.cpp:197: error: expected ‘;’ before ‘processbuf’
augment-bam.cpp:198: error: ‘processbuf’ was not declared in this scope
../cansam/cansam/sam/stream.h: At global scope:
../cansam/cansam/sam/stream.h:45: warning: ‘sam::sam_format’ defined but not used
make: *** [augment-bam.o] Error 1
make: Leaving directory `/ifs/work/leukgen/opt/BRASS-4.0.5/c++'
```

**Comment by keiranmraine** [comment]
Hi Kormal,

First try installing it into:

/path/to/BRASS-405/c++

Otherwise if you are able to install streams using a package manager I highly recommend it.  If not I’ll have to spend some time on a clean install to determine a successful method.

Let me now how you get on,

Regards,
Keiran

**Comment by komalsrathi** [comment]
Hi Keiran,

Pstreams documentation says that installing pstream.h is nothing but copying
the file to the desired folder. I tried cloning pstreams to
/path/to/Brass-405/c++ but still unable to install brass.

Also, forgot to mention that we are using a version controlled manner to
installed cgp tools. So, I usually edit the setup.sh file to add the
required Perl5libs after the unset statement and install the tools to
/path/to/software/version. This method has worked fine for all the cgp
tools' installations.

On Tuesday, January 26, 2016, Keiran Raine <notifications@github.com> wrote:

> Hi Kormal,
>
> First try installing it into:
>
> /path/to/BRASS-405/c++
>
> Otherwise if you are able to install streams using a package manager I
> highly recommend it. If not I’ll have to spend some time on a clean install
> to determine a successful method.
>
> Let me now how you get on,
>
> Regards,
> Keiran
>
> > On 25 Jan 2016, at 22:36, Komal Rathi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I don't have root access and I am using the build from here
> https://githubcom/cancerit/BRASS/archive/v405targz
> > I cloned pstreams using git clone git://gitcodesfnet/p/pstreams/code
> pstreams in /path/to/BRASS-405/ because setuplog says it is searching for
> pstreams/pstreamh But it is still unable to find the pstreamh file
> >
> > make: Entering directory `/ifs/work/leukgen/opt/BRASS-405/c++'
> > g++ -Wall -Wextra -g -I/cansam -O2 -c -o augment-bamo augment-bamcpp
> > augment-bamcpp:44:30: error: pstreams/pstreamh: No such file or directory
> > augment-bamcpp: In function ‘int main(int, char**)’:
> > augment-bamcpp:197: error: ‘redi’ has not been declared
> > augment-bamcpp:197: error: expected ‘;’ before ‘processbuf’
> > augment-bamcpp:198: error: ‘processbuf’ was not declared in this scope
> > /cansam/cansam/sam/streamh: At global scope:
> > /cansam/cansam/sam/streamh:45: warning: ‘sam::sam_format’ defined but
> not used
> > make: *** [augment-bamo] Error 1
> > make: Leaving directory `/ifs/work/leukgen/opt/BRASS-405/c++'
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cancerit/BRASS/issues/25>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cancerit/BRASS/issues/25#issuecomment-174916939>.
>


-- 
*Komal S Rathi* | Bioinformatics Engineer II, Memorial Sloan Kettering
Cancer Center | rathik@mskcc.org | komalr@mail.med.upenn.edu |
krathi1@jhu.edu <krathi1@live.johnshopkins.edu>

**Comment by keiranmraine** [comment]
Hi,

Can you try modifying the Makefile in the c++ folder to add the location of your pstream.h file:

    mkdir ~/include
    cp .../pstream.h ~/include/.

https://github.com/cancerit/BRASS/blob/dev/c%2B%2B/Makefile#L36

    CXXFLAGS = -Wall -Wextra -g -I$(CANSAM) -I~/include -O2

**Comment by keiranmraine** [comment]
FYI, I plan to add an optional environment variable to allow version based installs (basically doing what you have specified).

**Comment by komalsrathi** [comment]
Hi Keiran,

Thanks for the reply. I followed your instructions exactly:

```
# file is present in ~/include
$ ls ~/include/
pstream.h
```

```
CANSAM = ../cansam

# CXXFLAGS = -Wall -Wextra -g -I$(CANSAM) -O2
# edit made here
CXXFLAGS = -Wall -Wextra -g -I$(CANSAM) -I~/include -O2
LDFLAGS  = -L$(CANSAM)
```

but it is still throwing the following error:

```
g++ -Wall -Wextra -g -I../cansam -I~/include -O2   -c -o augment-bam.o augment-bam.cpp
augment-bam.cpp:44:30: error: pstreams/pstream.h: No such file or directory
augment-bam.cpp: In function ‘int main(int, char**)’:
augment-bam.cpp:197: error: ‘redi’ has not been declared
augment-bam.cpp:197: error: expected ‘;’ before ‘processbuf’
augment-bam.cpp:198: error: ‘processbuf’ was not declared in this scope
../cansam/cansam/sam/stream.h: At global scope:
../cansam/cansam/sam/stream.h:45: warning: ‘sam::sam_format’ defined but not used
make: *** [augment-bam.o] Error 1
make: Leaving directory `/ifs/work/leukgen/opt/BRASS-4.0.5/c++'
```

**Comment by komalsrathi** [comment]
Ok, so instead of the above solution, I did this:

clone pstreams to BRASS-4.0.5/c++
```
wget https://github.com/cancerit/BRASS/archive/v4.0.5.tar.gz
tar -zxf v4.0.5.tar.gz
cd BRASS-4.0.5/c++
git clone git://git.code.sf.net/p/pstreams/code pstreams
```

Then edit line 44 BRASS-4.0.5/c++/augment-bam.cpp (change #include <pstreams/pstream.h> to # include "pstreams/pstream.h")
```
# include "pstreams/pstream.h"
```

and now it is able to go beyond installing brass and velvet, which it wasn't getting past before:

```
$ ./setup.sh /ifs/work/leukgen/opt/cgp/5.18.4/brass/4.0.5
Max compilation CPUs set to 6
Installing build prerequisite Graph... done.
Building bedtools ... done.
Building blat ... done.
Building brass (c++)... done.
Building velvet... done.
Building exonerate...luna:BRASS-4.0.5 rathik$
```

But now, it is not able to install exonerate, this is my setup.log:

```
Using PTHREADS
----------------------------------------------------------------
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating doc/man/Makefile
config.status: creating doc/man/man1/Makefile
config.status: creating src/Makefile
config.status: creating src/general/Makefile
config.status: creating src/sequence/Makefile
config.status: creating src/database/Makefile
config.status: creating src/struct/Makefile
config.status: creating src/comparison/Makefile
config.status: creating src/c4/Makefile
config.status: creating src/bsdp/Makefile
config.status: creating src/sdp/Makefile
config.status: creating src/hub/Makefile
config.status: creating src/model/Makefile
config.status: creating src/program/Makefile
config.status: creating src/util/Makefile
config.status: creating test/Makefile
config.status: creating test/util/Makefile
config.status: creating test/ipcress/Makefile
config.status: creating test/exonerate/Makefile
config.status: creating test/data/Makefile
config.status: creating test/data/cdna/Makefile
config.status: creating test/data/protein/Makefile
cd . && autoconf
/usr/bin/perl: symbol lookup error: /ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5/x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_xs_apiversion_bootcheck
make: *** [configure] Error 127
```

I know I have to change `#!/usr/bin/perl` to the `/path/to/my/perl` that I am currently using but I can't figure out which file do I need to edit?

**Comment by keiranmraine** [comment]
Hi,

First, thanks for finding a solution for the stream issue, I may add this as a default behaviour to save others having this issue in future.

autoconfig always uses the system perl for installations, it’s not something that’s particularly nice to mess with (and annoying when it’s very outdated).

What have you added to your perl5lib variable?  There are some errors in some of the setup scripts indicating elements like the following:

	/ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5:/ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5/x86_64-linux-thread-multi

Change all of these to just include the base perl library folder and see how you get on:

	/ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5

This should then allow any native perl binary to search it’s own inbuilt paths first.

Sorry about this,

Keiran

**Comment by komalsrathi** [comment]
Currently, I have the following lines [130-134] added to setup.sh:

```
export PERL5LIB=$PERL5LIB:/ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5
export PERL5LIB=$PERL5LIB:/ifs/work/leukgen/opt/cgp/5.18.4/pcap/1.9.4/lib/perl5
export PERL5LIB=$PERL5LIB:/ifs/work/leukgen/opt/cgp/5.18.4/pcap/1.9.4/lib/perl5/x86_64-linux-thread-multi
export PERL5LIB=$PERL5LIB:/ifs/work/leukgen/opt/cgp/5.18.4/grass/1.1.3/lib/perl5
export PERL5LIB=$PERL5LIB:/ifs/work/leukgen/opt/cgp/5.18.4/grass/1.1.3/lib/perl5/x86_64-linux-thread-multi
```

But I don't understand why the error is referring to `/ifs/work/leukgen/opt/cgp/5.18.4/cgpVcf/1.2.2/lib/perl5/x86_64-linux-thread-multi` when I do not have in in the setup file.

**Comment by wushufly** [comment]
Thanks for the valuable solution. However, there is one place needed to be corrected about the 4th point below . The correction should be : # include "../pstreams/pstream.h"
1. wget https://github.com/cancerit/BRASS/archive/v4.0.5.tar.gz
tar -zxf v4.0.5.tar.gz
2. cd BRASS-4.0.5/c++
3. git clone git://git.code.sf.net/p/pstreams/code pstreams
4. Then edit line 44 BRASS-4.0.5/c++/augment-bam.cpp (change #include to # include "pstreams/pstream.h"):
 # include "pstreams/pstream.h"
