### ISSUE TITLE
Unreported Blat Dependency

### ISSUE THREAD

**Issue by jwhsanger** [cancerit/BRASS#28]
Hi Guys,

I have noted that there is now a dependency on the blat utility. It might be worth mentioning on the front page as this utility has a dramatically different licence agreement to the licence under which BRASS itself is being released.

As it is automatically downloaded as part of the setup.sh script mentioning up front might save people from being torpedoed.

:)

**Comment by keiranmraine** [comment]
No problem, I'll get it added, it's been there since the very first public migration though, nothing new.

Cheers for pointing it out.
