### ISSUE TITLE
match_rg_patterns_to_library.pl  could not pass the compilation

### ISSUE THREAD

**Issue by mailllonely** [cancerit/BRASS#40]
I have installed the BRASS 5.0.0 version in my linux computer.
When I run the match_rg_patterns_to_library.pl script, it could not pass the compilation.
It seems the script "Genome.pm" has bugs.

Throw following errors:
values on reference is experimental at BRASS-dev/perl/bin/../lib/Sanger/CGP/CopyNumber/Segment/Genome.pm line 473.
Compilation failed in require at ./match_rg_patterns_to_library.pl line 50.
BEGIN failed--compilation aborted at ./match_rg_patterns_to_library.pl line 50.

**Comment by keiranmraine** [comment]
Please use an up-to-date version, this was fixed in v5.1.4.  Current release is v5.1.5:

https://github.com/cancerit/BRASS/releases/tag/v5.1.5

**Comment by keiranmraine** [comment]
Hi , sorry this is a different issue to what I thought first thought and may take a few iterations to fix, are you able to pull from a hotfix branch?

**Comment by keiranmraine** [comment]
Okay.  So only a few very minor edits: https://github.com/cancerit/BRASS/commit/5fa6d244bd6d3b27b49711d28c867e12a6d46b69

Either checkout the hotfix branch: https://github.com/cancerit/BRASS/tree/hotfix/v5.1.6

Or pull the hotfix branch zip file and re-install: https://github.com/cancerit/BRASS/archive/hotfix/v5.1.6.zip

Please let me know if this is working and I will then merge and make a release.

Thank,
Keiran

**Comment by mailllonely** [comment]
Below is another bug I found here:

Use of uninitialized value in -e at /risapps/rhel6/brass/5.0.0/bin/brass.pl line 180

"copy($options->{'ascat_summary'}, $intdir) if(-e $options->{'ascat_summary'});"

Could you please let me know why?

**Comment by keiranmraine** [comment]
I've noted this as a new issue for tracking so will close this ticket and respond in #42
