### ISSUE TITLE
Values for optional field not being handled

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/BRASS#42]
Need to handle absence of sample stats file from [ascatNgs](https://github.com/cancerit/ascatNgs):

```
        -sampstat  -ss  ASCAT sample statistics file or file containing
                          NormalContamination 0.XXXXX [0.25]
                          Ploidy X.XXX [2.0]
```

If absent should apply the indicated default values.

**Comment by keiranmraine** [comment]
Info copied from unrelated item:

> Below is another bug I found here:
> 
> Use of uninitialized value in -e at /risapps/rhel6/brass/5.0.0/bin/brass.pl line 180
> 
> "copy($options->{'ascat_summary'}, $intdir) if(-e $options->{'ascat_summary'});"
> 
> Could you please let me know why?

**Comment by keiranmraine** [comment]
@mailllonely, Please upgrade to the [current release](https://github.com/cancerit/BRASS/releases), 5.0.0 is not a release just a tag.

The option '-samplestat' is not being handled correctly when absent.  You can work around this by creating a file as follows:

```
NormalContamination 0.25
Ploidy 2.0
```

If you have any information that could give you more accurate values please use them.  This is ideally generated by ascatNgs as indicated at the start of this ticket.

**Comment by mailllonely** [comment]
The sample statistical file from ASCAT is absent, and  I just created a file called "ascat.txt" including the following:

NormalContamination 0.25
Ploidy 2.0



then run the command: 

/risapps/rhel6/brass/5.0.0/bin/brass.pl -o /rsrch2/genomic_med/jli19/brass/ -t del/IPCT-FC117-MS16-Cap-889-8-ID40_160609-STJ00106-0174-BHCLC7BBXX-8-CTCAGA.bwa_recalibed.bam -n del/IPCT-FC117-TDEV0004-Cap-888-8-ID39_160609-STJ00106-0174-BHCLC7BBXX-7-CTATAC.bwa_recalibed.bam  -d /rsrch2/iacs/data/BRASS/ucscHiDepth_0.01_mrg1000_no_exon_coreChrs.bed.gz -g /scratch/rists/hpcapps/reference/human/broad_hg19/fastas/Homo_sapiens_assembly19.fasta -s human -as hg19 -pr WXS -gc /rsrch2/iacs/data/BRASS/Homo_sapiens.GRCh37.75.vagrent.cache.gz -vi /rsrch2/iacs/data/BRASS/viral.1.1.genomic.fa -mi /rsrch2/iacs/data/BRASS/all_ncbi_bacteria.20150703 -b /rsrch2/iacs/data/BRASS/hs37d5_500bp_windows.gc.bed.gz -ct /rsrch2/iacs/data/BRASS/Human.GRCh37.CentTelo.tsv.txt -sampstat  -ss ascat.txt 


it show the error below:
Option 'ascat_summary' (-ss) should be an existing file.

then I removed the parameter "-sampstat", it throw an error:

Failed to find 'NormalContamination' in /rsrch2/genomic_med/jli19/brass/ascat.txt

**Comment by keiranmraine** [comment]
Apologies it appears that the expected key for normal contamination is `rho`.  Change `NormalContamination` to `rho` and retry.  I'll create an issue to get the command line option corrected.

FYI: `-ss` and `-sampstat` are the same option so you should only define one.

**Comment by anoronh4** [comment]
i am having a similar issue. in the [dockstore-cgpwgs git](https://github.com/cancerit/dockstore-cgpwgs/blob/develop/scripts/analysisWGS.sh#L245-L277), we can supposedly run the `input` and `cover` steps without `ascat` results. however when using the latest dedicated BRASS docker: `quay.io/wtsicgp/brass:v6.3.4` you have to provide it, even when only running one of those two steps. 

has BRASS changed to require ascat for the previous steps as well? does it make sense to run those two steps in parallel with ascat, before running the remaining steps?
