### ISSUE TITLE
Visualising SV vcfs + Calling Fusions.

### ISSUE THREAD

**Issue by mortunco** [cancerit/BRASS#44]
Hi,

Thank you for processing ICGC data. I have obtained about ~250 patient vcfs from ICGC and I would to call a specific fusion based on delly output caused by a translocation.

1)What should be the best method for this kind of querry?
—> I thought visualising and deciding by my eye. This raised visualisation problem. Neither bedpe output nor vcf output helped out with the visualisation. (IGV and other genome browsers works but its really hard to asses translocation so I wanted to draw a circos plot.)

2) I have read about using snpEff or VEP(I am not sure about this). But as far as I know, snpEff does not support translocations so it won't work for my case.

3) Lastly, forgive my ignorance about the following terminology. Bedpe and reedname. Could you give me at least a source about this two file extensions ? (For example what is the difference btw bedpe and vcf. I know what is bed file but I couldnt link these together in structural variation subject.)

Sorry for asking bunch of questions. My graduate project is based on this data therefore, I am trying to process this information as good as possible.

Thank you for your patience,

Best,

Tunc/.

**Comment by keiranmraine** [comment]
Please see the wiki: https://github.com/cancerit/BRASS/wiki.

Other items do not relate to this package.  General questions as to how to handle data should be directed to a discussion forum such as BioStars.
