### ISSUE TITLE
error in normal contamination step

### ISSUE THREAD

**Issue by sb43** [cancerit/BRASS#45]
Warning: pcf is not run for sample 1 on chromosome arm  because all observations are missing. NA is returned.
Error in data.frame(rep(sampleid[i], nSeg), seg.chrom, seg.arm, pos.start,  : 
  arguments imply differing number of rows: 1, 0
Calls: pcf -> data.frame
In addition: Warning message:
In numericChrom(chrom) : NAs introduced by coercion
Execution halted

: could be due to non-nemric chromosme names in grch38

**Comment by CanWood** [comment]
I've just hit he same and I'm not using GRCh38.   I'm using 37.  Is there any information I can collect that would be of help in investigating this issue?

Cheers.

**Comment by CanWood** [comment]
I believe I've tracked this back to the SM tag in the @RG lines being the same in my tumour and normal bams, which leads to the same file being written to in the cover stages, and then read twice in the normcn stage.  That leads to the logratio being zero for everything, and the normcn chokes on it.

I'll try modifying Implement.pm to allow me to override the 'norm_name' and 'tum_name', as it won't, and I'll get back with results.

**Comment by sb43** [comment]
@CanWood I would suggest to re-header your bam files with modified RG line in one of the BAM file.
Also would you please check if the chromosome names have chr prefix?

**Comment by CanWood** [comment]
Thanks, Shiram,

The chr is consistent in my bam headers and all supporting files.  I'm not in a position to be able to re-head the bams, as I don't have the disk space for the whole set to be replicated.  We have a hundred or so tumour/normal whole genome pairs so it's 10s of TB.

I will rehead a couple of them, though,  to confirm that he rest of the pipe works.  Then I expect I'll need to adjust the use of tumour_name, tum_name, normal_name, norm_name, and sanitised_sample_from_bam, throughout.

At this point, I think it's pretty clear that the issue is with the inputs, rather than the code.
Cheers!

**Comment by CanWood** [comment]
Tumour bam reheaded, confirmed all inputs are consistently using "chr" and I'm still getting
```
In logratio - predict(gam_m) :
  longer object length is not a multiple of shorter object length
...
Warning: pcf is not run for sample 1 on chromosome arm  because all observations are missing. NA is returned.
Error in data.frame(rep(sampleid[i], nSeg), seg.chrom, seg.arm, pos.start,  : 
  arguments imply differing number of rows: 1, 0
Calls: pcf -> data.frame
In addition: Warning message:
In numericChrom(chrom) : NAs introduced by coercion
```
I had a look at the size of `logratio` and `predict(gam_m)` and they do differ:
logratio : 5722355
predict(gam_m) : 5722353

What could cause this discrepancy?

**Comment by sb43** [comment]
@CanWood  We have reproduced the errror and contacted the original author of this snippet.
Will get back to you at the earliest.
 Second error in  pcf function is due to chromosome prefix differences  and has been fixed in one of our feature branch feature/skip_CN_filter which is in testing phase and you are welcome to try it.
Please note that it requires cytoband file downloaded from UCSC table browser and chromosome nomenclature should match with the input bam file.

Thanks,
Shriram

**Comment by CanWood** [comment]
Thanks for taking the time to investigate, Shriram,

Glad to hear you have been able to reproduce the issue.  I'll re-recheck my bam files, genome, depth file, g_cache file, gcbins file, and centtel file, and ensure they are all using chr[1-22, X, Y] and re-run from the top, with the feature branch.  Again, if there is any further debugging I can run or information that I can provide that'll help, please let me know.

Cheers

**Comment by sb43** [comment]
@CanWood After quick discussion with original author I have filtered NA rows before applying gam function and results are identical.
Previous and current changes are in the chr_agnostic branch.

**Comment by sb43** [comment]
@CanWood  please note that these changes are now merged into dev branch and will be available in recent release

**Comment by CanWood** [comment]
Just got to testing this now. Error no longer presents. Thanks for the fix!

**Comment by sb43** [comment]
@CanWood  That's good know, I will close the thread.
