### ISSUE TITLE
Request: Docker installation file for distribution

### ISSUE THREAD

**Issue by evanbiederstedt** [cancerit/BRASS#47]
This is a reckless and improper request, but is it possible to create a Docker file to properly install this software? Considering the dependencies (and the time spent between myself and my system admin installing BRASS), it may be useful for replicable science. Your users would be very appreciative :)

**Comment by keiranmraine** [comment]
Hi,

We are currently in the process of generating a docker image using the [dockstore](https://dockstore.org) framework for the complete CGP analysis stack.  At present we have completed [dockstore-cgpmap](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap) but the WXS and WGS analysis pipelines should be available soon.

A legacy version of the WGS stack is available as a pre-built image [here](https://quay.io/repository/wtsicgp/cgp_in_a_box) and the dockerfile can be found [here](https://github.com/cancerit/cgpbox/blob/master/Dockerfile).

Regards,
Keiran
