### ISSUE TITLE
Help needed, velvet jobs being killed due to exonerate error

### ISSUE THREAD

**Issue by Hbm3085** [cancerit/BRASS#53]
Hi,

I am stuck at assembly step where exonerate is being invoked and iterations are terminating with the  error shown below:

`Aligning with --model affine:local for vertices: 3 at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/VelvetGraph.pm line 189.
exonerate --verbose 0 --showalignment no --showvulgar no --showcigar no --querytype dna --targettype dna --ryo %qas*Q %qab %qae %qS\n%tas*T %tab %tae %tS %ti\n** %qi %s\n --query /tmp/brassAssembly_IoE7e1/tmpHFkCrf/247-6cjOsk/65/brassAssExonerateHPtSjls.fa --target /tmp/brassAssembly_IoE7e1/tmpHFkCrf/247-6cjOsk/65/brassAssExonerateRef8lFNBiA.fa --percent 80 --model affine:local
Bio::Brass::Alignment::_run_exonerate(): Exonerate error: itteration: 1 (of 5), error code: 139, msg:  at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/Alignment.pm line 384.
Bio::Brass::Alignment::_run_exonerate(): Exonerate error: itteration: 2 (of 5), error code: 139, msg:  at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/Alignment.pm line 384.
Bio::Brass::Alignment::_run_exonerate(): Exonerate error: itteration: 3 (of 5), error code: 139, msg:  at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/Alignment.pm line 384.
Bio::Brass::Alignment::_run_exonerate(): Exonerate error: itteration: 4 (of 5), error code: 139, msg:  at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/Alignment.pm line 384.
Bio::Brass::Alignment::_run_exonerate(): Exonerate error: killed at itteration: 5 (of 5), error code: 139, msg:  at /opt/apps/bioinformatics/brass/5.3.3_threaded/lib/perl5/Bio/Brass/Alignment.pm line 384.
2.52user 1.52system 0:24.18elapsed 16%CPU (0avgtext+0avgdata 132268maxresident)k
0inputs+31032outputs (0major+116882minor)pagefaults 0swaps`

Complete error file attached.
[Sanger_CGP_Brass_Implement_assemble.3.err.txt](https://github.com/cancerit/BRASS/files/961743/Sanger_CGP_Brass_Implement_assemble.3.err.txt)

Any ideas/suggestions as to what is happening would be greatly appreciated!
Thanks!

**Comment by keiranmraine** [comment]
Can you confirm that the version of `exonerate` installed by `setup.sh` is the one in use and no other modifications were made?

For example the following two command should point to the same 'bin' location, based on your command I'd expect `/opt/apps/bioinformatics/brass/5.3.3_threaded/bin`
```
which brass.pl
which exonerate
```

**Comment by Hbm3085** [comment]
Thanks for your reply. Please see the output of the two commands below which both point to the same bin location
/opt/apps/bioinformatics/brass/5.3.3_threaded/bin/brass.pl
/opt/apps/bioinformatics/brass/5.3.3_threaded/bin/exonerate

Should I check anything else?
Thanks!

**Comment by keiranmraine** [comment]
We recommend using the docker image either directly of via singularity.  Should you be able to reproduce this we can investigate further.

Sorry it's been so long, this has been a low priority as we have not had any other reports of this problem.
