### ISSUE TITLE
Homozygous deletion no detected by BRASS

### ISSUE THREAD

**Issue by yuranymoreno** [cancerit/BRASS#54]
Dear all, 

Hoping you are having a great week. I am running BRASS for the identification of structural variants in a paired tumour and normal WGS data. Before I run BRASS, I checked a region, around 86 kb, on chr14 that I already knew it was deleted in both alleles using IGV. None reads mapped this region in the tumour sample, but it was completely fully covered with high depth in the germline sample.  Unfortunately, it was not annotated by BRASS/GRASS in the vcf file. Do you know why this is happening?

Thanks in advance for your help!

Yurany

**Comment by keiranmraine** [comment]
Sorry for the delay.  Can you check if there was evidence of aberrantly paired reads in the `*.brm.bam` files generated?  BRASS was designed around BWA-backtrack and requires multiple read pairs to map spanning the rearrangement and be tagged as improperly paired.

It is also worth examining the content of the `*.intermediates.tar.gz`, the file `*.groups.gz` will help you determine if the event was called but then filtered for some reason.

**Comment by keiranmraine** [comment]
No response
