### ISSUE TITLE
"keys on reference" warning prevents installation

### ISSUE THREAD

**Issue by ikirker** [cancerit/BRASS#62]
Installing BRASS 6.0.5 using Perl 5.22.0 (using the setup.sh script), I received this error:

```
PERL_DL_NONLAZY=1 "/shared/ucl/apps/perl/perlbrewroot/perls/perl-5.22.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/1_pm_compile.t ....... 3/? 
#   Failed test 'use Bio::Brass::Merge;'
#   at t/1_pm_compile.t line 67.
#     Tried to use 'Bio::Brass::Merge'.
#     Error:  keys on reference is experimental at /scratch/scratch/uccaiki/CancerIT-login05/BRASS-6.0.5/perl/blib/lib/Bio/Brass/Merge.pm line 159.
# Compilation failed in require at t/1_pm_compile.t line 67.
# BEGIN failed--compilation aborted at t/1_pm_compile.t line 67.
Bailout called.  Further testing stopped:  Unable to 'use' module Bio::Brass::Merge
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 6.
FAILED--Further testing stopped: Unable to 'use' module Bio::Brass::Merge
```

While this is normally a warning, it's been upgraded to an error by `use warnings FATAL => 'all';`.

If I'm reading this correctly, the [Perldoc on the keys function](https://perldoc.perl.org/functions/keys.html) suggests this should be removed in any case, since imminent versions of Perl will not let this work: 

> Starting with Perl 5.14, an experimental feature allowed keys to take a scalar expression. This experiment has been deemed unsuccessful, and was removed as of Perl 5.24.

The relevant line is: <https://github.com/cancerit/BRASS/blob/093163835e522d5242b04cfadd2b774f47387470/perl/lib/Bio/Brass/Merge.pm#L159>

I think this is fixable just by using `%{}` to convert the reference to a proper hash? 

```perl
my $most_reads = (sort {$a<=>$b} keys %{ $best{$most_samples} })[-1];
```

This seemed to remove the warning/error and let it install, anyway: I haven't checked the result.

**Comment by ikirker** [comment]
Ah! Thanks for the quick patch and release! 😅

**Comment by keiranmraine** [comment]
No problem, thanks for reporting, I thought I'd squashed all of these already (sadly the build takes too long for travis)
