### ISSUE TITLE
Centromere/telomere file doesn't agree with example

### ISSUE THREAD

**Issue by edawson** [cancerit/BRASS#69]
I've created a gist to create the centromere/telomere file for BRASS, but the data I get from UCSC doesn't agree with the example file provided. The only difference I can see is hg19 vs GRCh37.

My code is here: https://gist.github.com/edawson/83381e49ac8e5140d9f5519c91eccf24

Happy to fix and donate the script to the repo if it'd be useful.

**Comment by keiranmraine** [comment]
@edawson thanks for the gist, we'd happily accept a PR to pull it into the code base.

The documentation does indicate that the format isn't exactly the same, but having the script for the bulk of cases would be a good idea.

FYI you can get a pre-constructed set of reference files from here:

ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/CNV_SV_ref_GRCh37d5_brass6+.tar.gz

(note these do NOT have a `chr` prefix)

**Comment by edawson** [comment]
Sure! I've created PR https://github.com/cancerit/BRASS/pull/70 for this. Thank you for the reference files; I'll test on those as well.
