### ISSUE TITLE
depth parameter

### ISSUE THREAD

**Issue by gbnci** [cancerit/BRASS#74]
I have tried to run brass.pl but get error like:
"Option 'depth' has not been defined".
Not quite sure what I should put there. Should I put number like "-d ###", or file "-d file", if it is file, what file, bas file?  I have bas file generated in the same directory. Here is the  command line:
brass.pl -o outfolder -t tumor.bam -n normal.bam -r genome.fa;
the names of bas files are tumor.bam.bas and normal.bam.bas . Any suggestions would be appreciated.
Yonghong Wang

**Comment by AndyMenzies** [comment]
The depth option takes a file.  Have a look at the [BRASS wiki](https://github.com/cancerit/BRASS/wiki) here on github, it details how to obtain or generate the inputs.
