### ISSUE TITLE
error and quit for brass run

### ISSUE THREAD

**Issue by gbnci** [cancerit/BRASS#75]
I was running brass.pl but the process was quit with error like:

"/usr/bin/time teem/tmpBrass/logs/Sanger_CGP_Brass_Implement_input.1.sh 1> teem/tmpBrass/logs/Sanger_CGP_Brass_Implement_input.1.out 2> teem/tmpBrass/logs/Sanger_CGP_Brass_Implement_input.1.err" unexpectedly returned exit value 1 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 270.
 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 268

my command line is like:

brass.pl -o teem -t Tumor.realigned.md.bam -n Normal.realigned.md.bam -d depth_final.bed -g chr_genome.fa -s human -as GRCh37 -pr WGS -gc vagrent.human.GRCh37.homo_sapiens_91_37.cache.gz -vi viral.genomic.fa -mi all_bacteria.fa -b gcBins.bed -cb cytoband.txt -ct centTelo.tsv 

for the sh file generated, seems it added option like -p T -i:
#!/bin/bash
set -eux
bash -c 'set -o pipefail; /opt/wtsi-cgp/bin/samtools view -F 3854 -q 6 -u Tumor.realigned.md.bam | /opt/wtsi-cgp/bin/bedtools intersect
 -ubam -v -abam stdin -b depth_final.bed  | /opt/wtsi-cgp/biobambam2/bin/bamcollate2 outputformat=sam exclude= classes=F,F2 T=/teem/tmpBrass/bamcollate2_1 | /usr/bin/perl /opt/wtsi-cgp/bin/brassI_prep_bam.pl -b Tumor.realigned.md.bam.bas -p T 
-i  | /opt/wtsi-cgp/biobambam2/bin/bamsort tmpfile=/teem/tmpBrass/bamsort_1 inputformat=sam verbose=0 index=1 md5=1 md5filename=/teem/tmpBrass/Tumor.brm.bam.md5 indexfilename=/teem/tmpBrass/Tumor.brm.bam.bai O=/scratch/wangyong/all/teem/tmpBrass/Tumor.brm.bam'

The error file is:

+ bash -c 'set -o pipefail; /opt/wtsi-cgp/bin/samtools view -F 3854 -q 6 -u Tumor.realigned.md.bam | /opt/wtsi-cgp/bin/bedtools interse
ct -ubam -v -abam stdin -b /depth_final.bed  | /opt/wtsi-cgp/biobambam2/bin/bamcollate2 outputformat=sam exclude= classes=F,F2 T=/teem/tmpBrass/bamcollate2_1 | /usr/bin/perl /opt/wtsi-cgp/bin/brassI_prep_bam.pl -b /Tumor.realigned.md.bam.bas -p 
T -i  | /opt/wtsi-cgp/biobambam2/bin/bamsort tmpfile=/teem/tmpBrass/bamsort_1 inputformat=sam verbose=0 index=1 md5=1 md5filename=/teem/tmpBrass/Tumor.brm.bam.md5 indexfilename=/teem/tmpBrass/Tumor.brm.bam.bai O=teem/tmpBrass/Tumor.brm.bam'
Option i requires an argument
ScramDecoder::readAlignment(): failed to read alignment without reaching EOF

/opt/wtsi-cgp/biobambam2/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x2aaaaadb2e3c]
/opt/wtsi-cgp/biobambam2/bin/bamsort(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x420410]
/opt/wtsi-cgp/biobambam2/bin/bamsort()[0x448f53]
/opt/wtsi-cgp/biobambam2/bin/bamsort()[0x4191a1]
/opt/wtsi-cgp/biobambam2/bin/bamsort()[0x4124d5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x2aaaae52e830]
/opt/wtsi-cgp/biobambam2/bin/bamsort()[0x412be2]

WARNING: SAM header designates more than one PG tree root by PP tags.
Command exited with non-zero status 1
1.72user 0.26system 0:01.43elapsed 138%CPU (0avgtext+0avgdata 45492maxresident)k
11440inputs+32outputs (88major+12763minor)pagefaults 0swaps

It shows "Option i requires an argument". Not sure how this option gets into the command line and also how to solve the problem. Thanks for your help. By the way, in order to make the files less crowded, I have manually removed the absolute long path of most of my input files (if not all) in the content above.

regards
Yonghong

**Comment by moverm** [comment]
I get the same error. Did you fix the problem??

**Comment by keiranmraine** [comment]
Likely this would be caused in your cent-telo file had a mismatch in chromosome naming to that of the data you are processing:

https://github.com/cancerit/BRASS/wiki/Centromere-Telomere-locations
