### ISSUE TITLE
conda installation issues

### ISSUE THREAD

**Issue by alongalor** [cancerit/BRASS#82]
I installed brass via conda in a new conda environment:

```
conda create --name brass python=2.7
conda activate brass
conda install -c bioconda brass
```

The installation finished successfully (full output included below). I opened a new terminal window and typed:

```conda activate brass```

I `cd`'ed to `/home/my_user_name/anaconda3/envs/brass/` and tried to activate some of the brass-related packages without success. E.g.:
```
brass.pl
Can't locate PCAP/Cli.pm in @INC (you may need to install the PCAP::Cli module) (@INC contains: /home/ag457/anaconda3/envs/brass/bin/../lib/perl5/x86_64-linux-thread-multi /home/ag457/anaconda3/envs/brass/bin/../lib/perl5 /n/data1/hms/dbmi/park/alon/software/vcftools_0.1.13/perl /home/ag457/anaconda3/envs/brass/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ag457/anaconda3/envs/brass/lib/site_perl/5.26.2 /home/ag457/anaconda3/envs/brass/lib/5.26.2/x86_64-linux-thread-multi /home/ag457/anaconda3/envs/brass/lib/5.26.2 .) at /home/ag457/anaconda3/envs/brass/bin/brass.pl line 50.
BEGIN failed--compilation aborted at /home/ag457/anaconda3/envs/brass/bin/brass.pl line 50.
```

I realize I could go ahead and install all the packages as prompted, but as far as I understand the point of conda is to avoid this type of thing! Any help would be greatly appreciated!

Thanks a lot,

Alon
[terminal_output.txt](https://github.com/cancerit/BRASS/files/2968418/terminal_output.txt)

**Comment by keiranmraine** [comment]
We do not support the conda packaging of this tool, I'd suggest you need to have the conda package for PCAP-core also.
