### ISSUE TITLE
Is RC the same as SR?

### ISSUE THREAD

**Issue by ggrimes** [cancerit/BRASS#83]
Is the Read count (RC) the same as the number of Split Reads that support the variant?

Thanks

Graeme

**Comment by keiranmraine** [comment]
No,

Pairs spanning (PS) are those pairs where the insert size/orientation was disrupted and were used to form the group before refinement (aberrantly paired).

Reads contributing (RC) are those velvet indicated as being part of the assembly across the breakpoint.

```
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Count of pairs that span this breakpoint">
##FORMAT=<ID=RC,Number=1,Type=Integer,Description="Count of countributing reads">
```

(typo in that header line)

The split reads are only used "as is" in some of the filtering steps when trying to reduce the number of events passed to assembly.
