### ISSUE TITLE
pstream.h is missing

### ISSUE THREAD

**Issue by ink1** [cancerit/BRASS#9]
```
g++ -Wall -Wextra -g -I../cansam -O2   -c -o augment-bam.o augment-bam.cpp
augment-bam.cpp:32:30: error: pstreams/pstream.h: No such file or directory
```
Am I missing a package which provides it?

**Comment by keiranmraine** [comment]
You need to use the operating systems package manage to install ``libpstreams-dev``.

I'll add this to the docs for the next release.

**Comment by ink1** [comment]
libpstreams-dev is Ubuntu nomenclature. I'm effectively on a RH and there is nothing pstreams related. Any other clue?

**Comment by keiranmraine** [comment]
A quick Google for redhat pstreams suggests pstreams-devel

**Comment by ink1** [comment]
Eh, no. Not even in the latest RH7. I checked the pstreams source and it's just pstream.h file which has to be copied somewhere. I simply put it right in the c++ directory and modified augment-bam.cpp respectively. Understandably, this is not the most elegant solution but it worked for me.

**Comment by keiranmraine** [comment]
?
http://rpm.pbone.net/index.php3/stat/4/idpl/27125993/dir/redhat_el_7/com/pstreams-devel-0.7.0-5.el7.noarch.rpm.html

**Comment by ink1** [comment]
This is not a standard package. We don't install non-standard packages through system packagers on own systems. Everything extra goes into a separate folder.

**Comment by raylim** [comment]
You can download pstreams here: http://pstreams.sourceforge.net/download/
To install it, put pstream.h in include/pstreams

**Comment by komalsrathi** [comment]
I don't have root access so I created a folder pstreams in /path/to/BRASS-4.0.5/c++/ and copied pstream.h in it because setup.log says it is going in c++ and searching for pstreams/pstream.h. But it is still unable to find the pstream.h file.

```
make: Entering directory `/ifs/work/leukgen/opt/BRASS-4.0.5/c++'
g++ -Wall -Wextra -g -I../cansam -O2   -c -o augment-bam.o augment-bam.cpp
augment-bam.cpp:44:30: error: pstreams/pstream.h: No such file or directory
augment-bam.cpp: In function ‘int main(int, char**)’:
augment-bam.cpp:197: error: ‘redi’ has not been declared
augment-bam.cpp:197: error: expected ‘;’ before ‘processbuf’
augment-bam.cpp:198: error: ‘processbuf’ was not declared in this scope
../cansam/cansam/sam/stream.h: At global scope:
../cansam/cansam/sam/stream.h:45: warning: ‘sam::sam_format’ defined but not used
make: *** [augment-bam.o] Error 1
make: Leaving directory `/ifs/work/leukgen/opt/BRASS-4.0.5/c++'
```
