### ISSUE TITLE
Readgroup does not exist

### ISSUE THREAD

**Issue by podro182** [cancerit/BRASS#90]
Hi there and thanks for the well though out method :)

I'm trying to run brass 6.0.0 (I created all the required files as per wiki instructions),  however I'm encountering the following error: Readgroup 'A00559_78_HGMLJDRXX_3' does not exist.

I ran a sanity check with the picard tool ValidateSamFile and the BAM file seems ok. Plus the bam also plays well with other tools. I also checked that the readgroup is present in the header.

Do you have any suggestions on what might be wrong?

**Comment by keiranmraine** [comment]
This sounds like one of the following:

1. The records in the BAM file have `RG` aux tags that are not found in the header as `@RG` records.
2. Have you generated `bas` files using [`bam_stats`](https://github.com/cancerit/PCAP-core/wiki/Scripts-Generic#bam_stats-c)?

**Comment by podro182** [comment]
Thanks for the quick reply :)

1. The RG that gives the error is present in the header (error: `Readgroup 'A00559_78_HGMLJDRXX_3' does not exist`):
`@RG	ID:A00559_78_HGMLJDRXX_3	PL:ILLUMINA	PU:A00559_78_HGMLJDRXX_3	LB:XXX-Tumor-WGS_TruSeqUDI_A00559_0078	SM:XXX-Tumor-WGS_TruSeqUDI_A00559_0078	CN:RH-GM`

2. Yes, bas was generated like that: `bam_stats.pl -i $name'.bam' -o $name'.bam.bas'`

**Comment by keiranmraine** [comment]
Can you confirm the `*.bam.bas` file contains `A00559_78_HGMLJDRXX_3`

**Comment by podro182** [comment]
That's it, thanks a lot for the help!
For some reason this readgroup is missing
