### ISSUE TITLE
Generating an input bas?

### ISSUE THREAD

**Issue by cboursnell** [cancerit/BRASS#96]
Apologies if this has been asked before or this is a stupid question, but how do you generate a .bas file for an input .bam file?

**Comment by keiranmraine** [comment]
If you are using the container from [quay.io](https://quay.io/repository/wtsicgp/brass) (needs adding to readme/wiki) you can call `bam_stats` which is from one of the dependencies:

https://github.com/cancerit/PCAP-core/wiki/Scripts-Generic#bam_stats-c

If you have a native install `bam_stats` would have been installed as part of the PCAP-core dependency.
